apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "app-dpdt"
    meta.helm.sh/release-namespace: "diplom"

    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"labels":{"gitlab":"diplom","k8s-app":"app-dpdt","type":"local"},"name":"pg-data-pv"},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"200M"},"hostPath":{"path":"/usr/pg_data"},"storageClassName":"manual"}}
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2024-08-05T07:02:38Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    gitlab: diplom
    k8s-app: app-dpdt
    type: local
  name: pg-data-pv
  resourceVersion: "2081"
  uid: 1927c311-01bb-4d0a-8791-d8fdc68e9ae5
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 200M
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pg-data-pv-claim
    namespace: diplom
    resourceVersion: "2079"
    uid: 38d7770d-a60d-4c42-8d82-5a0a4ac49048
  hostPath:
    path: /usr/pg_data
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
status:
  phase: Bound
